# Generated by Django 5.1.8 on 2025-04-24 13:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['sent_at']},
        ),
        migrations.AddField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
